pipeline:
  backend:
    image: swift:latest
    commands:
        - echo "test"
        - eval "$(curl -sL https://apt.vapor.sh)"
        
      # - sudo apt-get install vapor
      # - sudo chmod -R a+rx /usr/
      # - swift build
      # - swift build -c release
      # - swift test

branches: master