version: '3.1'

volumes:
    postgres_db_data:
    portainer_data:

networks:
  loadbalancer-net:
  postgres-net:


services:

    postgres-db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_db_data:/var/lib/postgresql/data
        networks:
            - postgres-net
        environment:
            POSTGRES_USER: vapor
            POSTGRES_DB: vapor
            POSTGRES_PASSWORD: vapor


    apiserver:
        image: waddle/webserver
        command: ["./wait-for-it.sh", "postgres-db:5432", "--", "docker-entrypoint.sh"] 
        # ports:
        #    - "9000:9000"
        networks:
            - postgres-net
            - loadbalancer-net
        
        environment:
            POSTGRES_HOSTNAME: postgres-db
            POSTGRES_PORT: 5432
            POSTGRES_USER: vapor
            POSTGRES_PASSWORD: vapor
            POSTGRES_DB: vapor

            HASH_KEY: Oek4YdyUFmKmq3cH7nUWmOrV1JISackQbuWf+OooD3Y=
            CIPHER_KEY: Oek4YdyUFmKmq3cH7nUWmOrV1JISackQbuWf+OooD3Y=

        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 1
                delay: 10s
            labels:
                traefik.enable: "true"
                traefik.frontend.passHostHeader: "true"
                traefik.port: "9000"
                traefik.backend.loadbalancer.stickiness: "true"
                traefik.frontend.rule: "Host:api.waddle.test"


