version: '3.1'


volumes:
    postgres_db_data:

services:
    postgres-db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: vapor
            POSTGRES_DB: vapor
            POSTGRES_PASSWORD: vapor



